const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000),ROOT=path.join(__dirname,'..');
if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
if(!process.env.JWT_SECRET) throw new Error('JWT_SECRET is required');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}});
const json=(res,code,obj)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':process.env.FRONTEND_ORIGIN||'*','Access-Control-Allow-Headers':'Content-Type,Authorization,X-Admin-Key','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS'});res.end(JSON.stringify(obj))};
const body=req=>new Promise((resolve,reject)=>{let s='';req.on('data',x=>{s+=x;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})});
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(String(p),salt,64).toString('hex')};
const verify=(p,stored)=>{const [salt,h]=String(stored).split(':');if(!salt||!h)return false;const g=crypto.scryptSync(String(p),salt,64).toString('hex');return g.length===h.length&&crypto.timingSafeEqual(Buffer.from(g),Buffer.from(h))};
const sign=u=>{const p=Buffer.from(JSON.stringify({id:u.id,exp:Date.now()+7*864e5})).toString('base64url');return p+'.'+crypto.createHmac('sha256',process.env.JWT_SECRET).update(p).digest('base64url')};
async function auth(req){try{const [p,s]=(req.headers.authorization||'').replace(/^Bearer\s+/,'').split('.');if(!p||!s)return null;const e=crypto.createHmac('sha256',process.env.JWT_SECRET).update(p).digest('base64url');if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const x=JSON.parse(Buffer.from(p,'base64url'));if(!x.id||x.exp<Date.now())return null;const r=await pool.query('SELECT id,name,email,referral_code,wallet_balance,role,status FROM users WHERE id=$1',[x.id]);return r.rows[0]?.status==='active'?r.rows[0]:null}catch{return null}}
const safe=u=>({id:u.id,name:u.name,email:u.email,balance:Number(u.wallet_balance),referralCode:u.referral_code,role:u.role});
function sendFile(res,file){const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}
async function admin(req){const k=process.env.ADMIN_KEY;return !!k&&req.headers['x-admin-key']===k}
async function route(req,res){if(req.method==='OPTIONS')return json(res,204,{});const u=new URL(req.url,'http://localhost');
if(req.method==='GET'&&u.pathname==='/api/health'){try{await pool.query('SELECT 1');return json(res,200,{ok:true,database:'postgresql'})}catch{return json(res,503,{ok:false,error:'Database unavailable'})}}
if(req.method==='GET'&&u.pathname==='/api/tasks'){const r=await pool.query('SELECT id,title,description,reward FROM tasks WHERE active=true ORDER BY created_at DESC');return json(res,200,{tasks:r.rows.map(x=>({...x,reward:Number(x.reward)}))})}
if(req.method==='POST'&&u.pathname==='/api/register'){const b=await body(req),email=String(b.email||'').trim().toLowerCase();if(!b.name||!/^\S+@\S+\.\S+$/.test(email)||String(b.password||'').length<8)return json(res,400,{error:'Name, valid email and password (8+ chars) required'});const c=await pool.connect();try{await c.query('BEGIN');if((await c.query('SELECT 1 FROM users WHERE email=$1',[email])).rowCount){await c.query('ROLLBACK');return json(res,409,{error:'Email already registered'})}let ref=null;if(b.referralCode){const q=await c.query("SELECT id FROM users WHERE referral_code=$1 AND status='active'",[String(b.referralCode).trim()]);if(q.rowCount)ref=q.rows[0].id}const id=crypto.randomUUID(),code='ET'+id.replace(/-/g,'').slice(0,8).toUpperCase();const q=await c.query('INSERT INTO users(id,name,email,password_hash,referral_code,referred_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,email,referral_code,wallet_balance,role,status',[id,String(b.name).trim(),email,hash(b.password),code,ref]);if(ref)await c.query('INSERT INTO referrals(id,referrer_id,referee_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[crypto.randomUUID(),ref,id]);await c.query('COMMIT');return json(res,201,{user:safe(q.rows[0]),token:sign(q.rows[0])})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
if(req.method==='POST'&&u.pathname==='/api/login'){const b=await body(req),q=await pool.query('SELECT id,name,email,password_hash,referral_code,wallet_balance,role,status FROM users WHERE email=$1',[String(b.email||'').trim().toLowerCase()]),x=q.rows[0];if(!x||x.status!=='active'||!verify(b.password,x.password_hash))return json(res,401,{error:'Invalid email or password'});return json(res,200,{user:safe(x),token:sign(x)})}
const user=await auth(req);if(!user)return json(res,401,{error:'Login required'});
if(req.method==='GET'&&u.pathname==='/api/me')return json(res,200,{user:safe(user)});
if(req.method==='GET'&&u.pathname==='/api/transactions'){const q=await pool.query('SELECT id,type,amount,status,created_at AS "createdAt" FROM transactions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200',[user.id]);return json(res,200,{transactions:q.rows.map(x=>({...x,amount:Number(x.amount)}))})}
if(req.method==='POST'&&u.pathname==='/api/tasks/complete'){const b=await body(req),c=await pool.connect();try{await c.query('BEGIN');const t=await c.query('SELECT id,reward FROM tasks WHERE id=$1 AND active=true FOR UPDATE',[b.taskId]);if(!t.rowCount){await c.query('ROLLBACK');return json(res,404,{error:'Task not found'})}const task=t.rows[0];const dup=await c.query("SELECT id FROM task_completions WHERE user_id=$1 AND task_id=$2 AND completed_at>=CURRENT_DATE AND completed_at<CURRENT_DATE+INTERVAL '1 day' LIMIT 1",[user.id,task.id]);if(dup.rowCount){await c.query('ROLLBACK');return json(res,409,{error:'Already completed today'})}const reward=Number(task.reward);await c.query('INSERT INTO task_completions(id,user_id,task_id,reward) VALUES($1,$2,$3,$4)',[crypto.randomUUID(),user.id,task.id,reward]);const q=await c.query('UPDATE users SET wallet_balance=wallet_balance+$1 WHERE id=$2 RETURNING wallet_balance',[reward,user.id]);await c.query('INSERT INTO transactions(id,user_id,type,amount,status,reference) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),user.id,'task_reward',reward,'credited',task.id]);await c.query('COMMIT');return json(res,200,{message:'Reward credited',balance:Number(q.rows[0].wallet_balance)})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
if(req.method==='POST'&&u.pathname==='/api/withdrawals'){const b=await body(req),amount=Number(b.amount),upi=String(b.upiId||'').trim();if(!Number.isFinite(amount)||amount<100)return json(res,400,{error:'Minimum withdrawal is ₹100'});if(!/^\S+@\S+$/.test(upi))return json(res,400,{error:'Valid UPI ID required'});const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT wallet_balance FROM users WHERE id=$1 FOR UPDATE',[user.id]);const bal=Number(q.rows[0].wallet_balance);if(amount>bal){await c.query('ROLLBACK');return json(res,400,{error:'Insufficient balance'})}const wid=crypto.randomUUID();await c.query('UPDATE users SET wallet_balance=wallet_balance-$1 WHERE id=$2',[amount,user.id]);await c.query('INSERT INTO withdrawals(id,user_id,amount,method,destination,status) VALUES($1,$2,$3,$4,$5,$6)',[wid,user.id,amount,'UPI',upi,'pending']);await c.query('INSERT INTO transactions(id,user_id,type,amount,status,reference) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),user.id,'withdrawal',-amount,'pending',wid]);await c.query('COMMIT');return json(res,201,{withdrawal:{id:wid,status:'pending'},balance:bal-amount})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
if(req.method==='GET'&&u.pathname==='/api/admin/stats'){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const [a,b,c,d]=await Promise.all([pool.query('SELECT COUNT(*)::int n FROM users'),pool.query('SELECT COUNT(*)::int n FROM tasks'),pool.query("SELECT COUNT(*)::int n FROM withdrawals WHERE status='pending'"),pool.query('SELECT COALESCE(SUM(wallet_balance),0)::numeric n FROM users')]);return json(res,200,{users:a.rows[0].n,tasks:b.rows[0].n,pendingWithdrawals:c.rows[0].n,walletLiability:Number(d.rows[0].n)})}
if(req.method==='GET'&&u.pathname==='/api/admin/users'){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const q=await pool.query('SELECT id,name,email,wallet_balance,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 500');return json(res,200,{users:q.rows.map(x=>({...x,wallet_balance:Number(x.wallet_balance)}))})}
if(req.method==='GET'&&u.pathname==='/api/admin/tasks'){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const q=await pool.query('SELECT * FROM tasks ORDER BY created_at DESC');return json(res,200,{tasks:q.rows.map(x=>({...x,reward:Number(x.reward)}))})}
if(req.method==='POST'&&u.pathname==='/api/admin/tasks'){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const b=await body(req),reward=Number(b.reward);if(!b.title||!Number.isFinite(reward)||reward<0)return json(res,400,{error:'Title and valid reward required'});const q=await pool.query('INSERT INTO tasks(id,title,description,reward,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[crypto.randomUUID(),String(b.title).trim(),String(b.description||''),reward,b.active!==false]);return json(res,201,{task:{...q.rows[0],reward:Number(q.rows[0].reward)}})}
if(req.method==='PATCH'&&u.pathname.startsWith('/api/admin/tasks/')){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const id=u.pathname.split('/').pop(),b=await body(req);const q=await pool.query('UPDATE tasks SET title=COALESCE($1,title),description=COALESCE($2,description),reward=COALESCE($3,reward),active=COALESCE($4,active) WHERE id=$5 RETURNING *',[b.title??null,b.description??null,b.reward==null?null:Number(b.reward),b.active==null?null:Boolean(b.active),id]);if(!q.rowCount)return json(res,404,{error:'Task not found'});return json(res,200,{task:{...q.rows[0],reward:Number(q.rows[0].reward)}})}
if(req.method==='GET'&&u.pathname==='/api/admin/withdrawals'){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const q=await pool.query('SELECT w.id,w.user_id,u.email,u.name,w.amount,w.method,w.destination,w.status,w.admin_note,w.created_at FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.created_at DESC LIMIT 500');return json(res,200,{withdrawals:q.rows.map(x=>({...x,amount:Number(x.amount)}))})}
if(req.method==='PATCH'&&u.pathname.startsWith('/api/admin/withdrawals/')){if(!await admin(req))return json(res,403,{error:'Admin access denied'});const id=u.pathname.split('/').pop(),b=await body(req);if(!['approved','rejected','pending'].includes(b.status))return json(res,400,{error:'Invalid status'});const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM withdrawals WHERE id=$1 FOR UPDATE',[id]);if(!q.rowCount){await c.query('ROLLBACK');return json(res,404,{error:'Withdrawal not found'})}const w=q.rows[0];if(w.status==='pending'&&b.status==='rejected')await c.query('UPDATE users SET wallet_balance=wallet_balance+$1 WHERE id=$2',[w.amount,w.user_id]);await c.query('UPDATE withdrawals SET status=$1,admin_note=$2,processed_at=CASE WHEN $1 IN (\'approved\',\'rejected\') THEN NOW() ELSE NULL END WHERE id=$3',[b.status,String(b.note||''),id]);await c.query('UPDATE transactions SET status=$1 WHERE reference=$2',[b.status,id]);await c.query('COMMIT');return json(res,200,{ok:true,status:b.status})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
if(req.method==='GET'&&u.pathname==='/')return sendFile(res,path.join(ROOT,'index.html'));if(req.method==='GET'&&!u.pathname.startsWith('/api/')){const file=path.join(ROOT,u.pathname.replace(/^\//,''));if(file.startsWith(ROOT)&&fs.existsSync(file)&&fs.statSync(file).isFile())return sendFile(res,file)}return json(res,404,{error:'Not found'})}
http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);json(res,500,{error:'Server error'})})).listen(PORT,()=>console.log('EarnTask API running on '+PORT));
