services:
  - type: web
    name: earntask-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: PGSSL
        value: "require"
